name: Auto PR to Main

on:
  push:
    branches:
      - 'feature/**'
      - 'bugfix/**'

jobs:
  open-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Extract branch name
        id: extract_branch
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: Check if PR already exists
        id: check
        uses: actions/github-script@v7
        with:
          script: |
            const branch = process.env.BRANCH_NAME;
            const { data: prs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              head: `${context.repo.owner}:${branch}`,
              base: 'main'
            });
            core.setOutput('exists', prs.length > 0);

      - name: Create Pull Request
        if: steps.check.outputs.exists == 'false'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          base: main
          branch: ${{ env.BRANCH_NAME }}
          title: "Auto PR: ${{ env.BRANCH_NAME }} → main"
          body: "This PR was created automatically after a push to `${{ env.BRANCH_NAME }}`."
